version: '3'
services:
  eosio-cdt:
    image: eostudio/eosio.cdt:v1.7.0
    container_name: 'eosio-cdt'
    volumes:
      - ./:/var/repo
  dfuse:
    build:
      context: ./blockchain
      dockerfile: Dockerfile-dfuse
    container_name: "dfuse"
    ports:
      - 8080:8080
      - 8081:8081
      - 8888:8888
    volumes:
      - ./:/var/repo
      - ./temp/dfuse:/data
    command: ["dfuseeos", "start", "--data-dir", "/data"]
  mongo:
    image: mongo:4.2.7
    container_name: 'mongodb'
    ports:
      - 27017:27017
    environment:
      - MONGO_DATA_DIR=/data
      - MONGO_LOG_DIR=/data-logs
      - MONGODB_USER="user"
      - MONGODB_PASS="pass"
    volumes:
      - ./temp/mongo/db:/data/db
      - ./temp/mongo/configdb:/data/configdb
      - ./temp/mongo/logs:/data-logs