version: '3'

volumes:
  blockchain-data:
    external:
      name: blockchain-data
  mongo-data:
    external:
      name: mongo-data
    
services:
  dfuse:
    build:
      context: ./blockchain
    container_name: "dfuse"
    ports:
      - 8080:8080
      - 8081:8081
      - 8888:8888
    environment:
      - REACT_APP_DFUSE_AUTH_URL=null://
      - REACT_APP_DFUSE_API_KEY=abc
      - REACT_APP_DFUSE_API_NETWORK=blockchain-civic.conscious-cities.com
    volumes:
      - ./:/var/repo
      - blockchain-data:/data
    command: "/var/repo/blockchain/entrypoint.sh"
  mongo:
    image: mongo:4.2.7
    container_name: 'mongodb'
    ports:
      - 27017:27017
    environment:
      - MONGO_DATA_DIR=/data
      - MONGO_LOG_DIR=/data-logs
      - MONGODB_USER="user"
      - MONGODB_PASS="pass"
    volumes:
      - mongo-data:/data/db