version: '3'

volumes:
  blockchain-data:
    external:
      name: blockchain-data
  mongo-data:
    external:
      name: mongo-data
    
services:
  dfuse:
    build:
      context: ./blockchain
    container_name: "dfuse"
    ports:
      - 8080:8080
      - 8081:8081
      - 8888:8888
    environment:
      - EOSQ_ENDPOINT_URL=$EOSQ_ENDPOINT_URL
    volumes:
      - ./:/var/repo
      - blockchain-data:/data
    command: ["dfuseeos", "start", "--data-dir", "/data", "--search-common-dfuse-events-action-name=dfuseiohooks:event", "--search-common-dfuse-events-unrestricted=true", "--common-chain-id", "df383d1cc33cbb9665538c604daac13706978566e17e5fd5f897eff68b88e1e4", "--eosq-api-endpoint-url=${EOSQ_ENDPOINT_URL}"]
  mongo:
    image: mongo:4.2.7
    container_name: 'mongodb'
    ports:
      - 27017:27017
    environment:
      - MONGO_DATA_DIR=/data
      - MONGO_LOG_DIR=/data-logs
      - MONGODB_USER="user"
      - MONGODB_PASS="pass"
    volumes:
      - mongo-data:/data/db